---
- name: Install ZSH
  package:
    name: "{{ item }}"
  become: yes
  loop:
  - zsh
  - curl
  - wget
- name: Download Oh-My-ZSH
  get_url:
    dest: ~/oh-my-zsh-install.sh
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    mode: '0660'
  become: yes
  become_user: "{{ target_user }}"
- name: Install Oh-My-ZSH
  command: bash ~/oh-my-zsh-install.sh
  become: yes
  become_user: "{{ target_user }}"
